const Grammar = require("./classGrammar.js");

const grammar = new Grammar();

// generating strings
const generatedStrings = grammar.generateStrings();
console.log("Generated Strings:");
console.log(generatedStrings);

// converting to finite automaton
const automaton = grammar.toFiniteAutomaton();
console.log("\nFinite Automaton:");
console.log(automaton);

// checking if a string can be generated by the automaton
const inputString = "aaaa";
console.log(
  `\nCan '${inputString}' be generated by the automaton? ${automaton.canBeGenerated(
    inputString
  )}`
);
